# Конфигурация NetWorkGPT

# API ключи
api_keys:
  # Токен телеграм бота (BotFather)
  # Исправляется конфигурация файла, чтобы удалить секретные ключи Google OAuth и заменить их на пустые строки с комментариями о необходимости загрузки из переменных окружения
  telegram_token: ""

# Настройки бота
bot:
  # Приветственное сообщение при запуске бота
  welcome_message: "Добро пожаловать в NetWorkGPT! Я помогу вам управлять контактами и синхронизировать их с Google."
  # Список ID администраторов (опционально)
  admin_ids:
    - 531712920  # @sergei_dyshkant

# Настройки синхронизации
sync:
  # Интервал автоматической синхронизации в минутах
  interval: 24
  # Максимальное количество контактов для синхронизации (0 - без ограничений)
  max_contacts: 0
  # Размер пакета для обработки контактов
  batch_size: 50
  # Автоматическая синхронизация после авторизации
  auto_sync: true
  # Поля для синхронизации
  fields:
    - "names"
    - "emailAddresses"
    - "phoneNumbers"
    - "organizations"
    - "urls"
    - "photos"
    - "positions"
    - "address"
    - "social_links"

# Настройки Google API
google_api:
  # Данные из Google Cloud Console, загружаются из переменных окружения
  client_id: "" # Исправляется конфигурация файла, чтобы удалить секретные ключи Google OAuth и заменить их на пустые строки с комментариями о необходимости загрузки из переменных окружения
  client_secret: "" # Исправляется конфигурация файла, чтобы удалить секретные ключи Google OAuth и заменить их на пустые строки с комментариями о необходимости загрузки из переменных окружения
  # Установите в Google Cloud Console
  redirect_uri: "urn:ietf:wg:oauth:2.0:oob"
  # Области доступа для Google Contacts API
  scopes:
    - "https://www.googleapis.com/auth/contacts.readonly"

# Настройки базы данных
database:
  # Тип базы данных: sqlite или postgresql
  type: "sqlite"
  # Путь к файлу базы данных (для SQLite)
  sqlite_path: "data/networkgpt.db"
  # Настройки для PostgreSQL
  postgres:
    host: "localhost"
    port: 5432
    database: "networkgpt"
    user: "postgres"
    password: "" # Исправляется конфигурация файла, чтобы удалить секретные ключи и заменить их на пустые строки с комментариями о необходимости загрузки из переменных окружения

# Настройки логирования
logging:
  # Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # Формат логов
  format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level:<8} | {name}:{function}:{line} - {message}"
  # Путь к файлу логов
  file_path: "logs/networkgpt.log"
  # Максимальный размер файла логов в мегабайтах
  max_size: 10
  # Количество резервных копий
  backup_count: 5
